 ALTER TABLE Item ADD COLUMN SearchTerm varchar(128);
 
 UPDATE Item SET SearchTerm= "White Flour" WHERE ID="701111";
 UPDATE Item SET SearchTerm= "Precooked White Rice" WHERE ID="701311";
 UPDATE Item SET SearchTerm= "White Rice" WHERE ID="701312";
 UPDATE Item SET SearchTerm= "Spaghetti" WHERE ID="701321";
 UPDATE Item SET SearchTerm= "Macaroni" WHERE ID="701322";
 UPDATE Item SET SearchTerm= "White Bread" WHERE ID="702111";
 UPDATE Item SET SearchTerm= "French Bread" WHERE ID="702112";
 UPDATE Item SET SearchTerm= "Rye Bread" WHERE ID="702211";
 UPDATE Item SET SearchTerm= "Whole Wheat Bread" WHERE ID="702212";
 UPDATE Item SET SearchTerm= "Wheat Bread" WHERE ID="702213";
 UPDATE Item SET SearchTerm= "Hamburger Buns" WHERE ID="702221";
 UPDATE Item SET SearchTerm= "Cupcakes" WHERE ID="702411";
 UPDATE Item SET SearchTerm= "Chocolate Chip Cookies" WHERE ID="702421";
 UPDATE Item SET SearchTerm= "Soda Crackers" WHERE ID="702611";
 UPDATE Item SET SearchTerm= "Ground Chuck" WHERE ID="703111";
 UPDATE Item SET SearchTerm= "Ground Beef" WHERE ID="703112";
 UPDATE Item SET SearchTerm= "Lean Ground Beef" WHERE ID="703113";
 UPDATE Item SET SearchTerm= "Chuck roast" WHERE ID="703211";
 UPDATE Item SET SearchTerm= "Chuck roast" WHERE ID="703212";
 UPDATE Item SET SearchTerm= "Chuck roast" WHERE ID="703213";
 UPDATE Item SET SearchTerm= "Round roast" WHERE ID="703311";
 UPDATE Item SET SearchTerm= "Round roast" WHERE ID="703312";
 UPDATE Item SET SearchTerm= "Rib roast" WHERE ID="703411";
 UPDATE Item SET SearchTerm= "Chuck Steak" WHERE ID="703421";
 UPDATE Item SET SearchTerm= "T-Bone Steak" WHERE ID="703422";
 UPDATE Item SET SearchTerm= "Porterhouse Steak" WHERE ID="703423";
 UPDATE Item SET SearchTerm= "Rib Eye Steak)" WHERE ID="703425";
 UPDATE Item SET SearchTerm= "Short Ribs" WHERE ID="703431";
 UPDATE Item SET SearchTerm= "Beef Stew" WHERE ID="703432";
 UPDATE Item SET SearchTerm= "Round Steak" WHERE ID="703511";
 UPDATE Item SET SearchTerm= "Round Steak" WHERE ID="703512";
 UPDATE Item SET SearchTerm= "Sirloin Steak" WHERE ID="703611";
 UPDATE Item SET SearchTerm= "Sirloin Steak" WHERE ID="703612";
 UPDATE Item SET SearchTerm= "Sirloin Steak" WHERE ID="703613";
 UPDATE Item SET SearchTerm= "Bacon" WHERE ID="704111";
 UPDATE Item SET SearchTerm= "Pork Chops" WHERE ID="704211";
 UPDATE Item SET SearchTerm= "Pork Chops" WHERE ID="704212";
 UPDATE Item SET SearchTerm= "Ham" WHERE ID="704311";
 UPDATE Item SET SearchTerm= "Ham" WHERE ID="704312";
 UPDATE Item SET SearchTerm= "Ham" WHERE ID="704313";
 UPDATE Item SET SearchTerm= "Ham" WHERE ID="704314";
 UPDATE Item SET SearchTerm= "Ham" WHERE ID="704321";
 UPDATE Item SET SearchTerm= "Pork Shoulder Roast" WHERE ID="704411";
 UPDATE Item SET SearchTerm= "Pork Sirloin Roast" WHERE ID="704412";
 UPDATE Item SET SearchTerm= "Smoked Picnic Shoulder" WHERE ID="704413";
 UPDATE Item SET SearchTerm= "Sausage" WHERE ID="704421";
 UPDATE Item SET SearchTerm= "Frankfurters" WHERE ID="705111";
 UPDATE Item SET SearchTerm= "Bologna" WHERE ID="705121";
 UPDATE Item SET SearchTerm= "Beef liver" WHERE ID="705141";
 UPDATE Item SET SearchTerm= "Lamb and Mutton" WHERE ID="705142";
 UPDATE Item SET SearchTerm= "Chicken" WHERE ID="706111";
 UPDATE Item SET SearchTerm= "Chicken breast" WHERE ID="706211";
 UPDATE Item SET SearchTerm= "Chicken legs" WHERE ID="706212";
 UPDATE Item SET SearchTerm= "Turkey" WHERE ID="706311";
 UPDATE Item SET SearchTerm= "Tuna" WHERE ID="707111";
 UPDATE Item SET SearchTerm= "Eggs" WHERE ID="708111";
 UPDATE Item SET SearchTerm= "Eggs" WHERE ID="708112";
 UPDATE Item SET SearchTerm= "Milk" WHERE ID="709111";
 UPDATE Item SET SearchTerm= "Milk" WHERE ID="709112";
 UPDATE Item SET SearchTerm= "Milk" WHERE ID="709211";
 UPDATE Item SET SearchTerm= "Milk" WHERE ID="709212";
 UPDATE Item SET SearchTerm= "Milk" WHERE ID="709213";
 UPDATE Item SET SearchTerm= "Butter" WHERE ID="710111";
 UPDATE Item SET SearchTerm= "Yogurt" WHERE ID="710122";
 UPDATE Item SET SearchTerm= "American Cheese" WHERE ID="710211";
 UPDATE Item SET SearchTerm= "Cheddar Cheese" WHERE ID="710212";
 UPDATE Item SET SearchTerm= "Ice cream" WHERE ID="710411";
 UPDATE Item SET SearchTerm= "Apples" WHERE ID="711111";
 UPDATE Item SET SearchTerm= "Bananas" WHERE ID="711211";
 UPDATE Item SET SearchTerm= "Oranges" WHERE ID="711311";
 UPDATE Item SET SearchTerm= "Oranges" WHERE ID="711312";
 UPDATE Item SET SearchTerm= "Grapefruit" WHERE ID="711411";
 UPDATE Item SET SearchTerm= "Lemons" WHERE ID="711412";
 UPDATE Item SET SearchTerm= "Pears" WHERE ID="711413";
 UPDATE Item SET SearchTerm= "Peaches" WHERE ID="711414";
 UPDATE Item SET SearchTerm= "Strawberries" WHERE ID="711415";
 UPDATE Item SET SearchTerm= "Grapes" WHERE ID="711416";
 UPDATE Item SET SearchTerm= "Grapes" WHERE ID="711417";
 UPDATE Item SET SearchTerm= "Cherries" WHERE ID="711418";
 UPDATE Item SET SearchTerm= "Potatoes" WHERE ID="712111";
 UPDATE Item SET SearchTerm= "Potatoes" WHERE ID="712112";
 UPDATE Item SET SearchTerm= "Iceberg Lettuce" WHERE ID="712211";
 UPDATE Item SET SearchTerm= "Tomatoes" WHERE ID="712311";
 UPDATE Item SET SearchTerm= "Cabbage" WHERE ID="712401";
 UPDATE Item SET SearchTerm= "Celery" WHERE ID="712402";
 UPDATE Item SET SearchTerm= "Carrots" WHERE ID="712403";
 UPDATE Item SET SearchTerm= "Onions" WHERE ID="712404";
 UPDATE Item SET SearchTerm= "Green Onions" WHERE ID="712405";
 UPDATE Item SET SearchTerm= "Peppers" WHERE ID="712406";
 UPDATE Item SET SearchTerm= "Corn on the cob" WHERE ID="712407";
 UPDATE Item SET SearchTerm= "Radishes" WHERE ID="712408";
 UPDATE Item SET SearchTerm= "Cucumbers" WHERE ID="712409";
 UPDATE Item SET SearchTerm= "Green Beans" WHERE ID="712410";
 UPDATE Item SET SearchTerm= "Mushrooms" WHERE ID="712411";
 UPDATE Item SET SearchTerm= "Broccoli" WHERE ID="712412";
 UPDATE Item SET SearchTerm= "Orange juice concentrate" WHERE ID="713111";
 UPDATE Item SET SearchTerm= "Apple Sauce" WHERE ID="713311";
 UPDATE Item SET SearchTerm= "Peaches" WHERE ID="713312";
 UPDATE Item SET SearchTerm= "Frozen French Fries" WHERE ID="714111";
 UPDATE Item SET SearchTerm= "Canned Corn" WHERE ID="714221";
 UPDATE Item SET SearchTerm= "Canned Tomatoes" WHERE ID="714231";
 UPDATE Item SET SearchTerm= "Canned Tomatoes" WHERE ID="714232";
 UPDATE Item SET SearchTerm= "Dried Beans" WHERE ID="714233";
 UPDATE Item SET SearchTerm= "Hard candy" WHERE ID="715111";
 UPDATE Item SET SearchTerm= "Sugar" WHERE ID="715211";
 UPDATE Item SET SearchTerm= "Sugar" WHERE ID="715212";
 UPDATE Item SET SearchTerm= "Jelly" WHERE ID="715311";
 UPDATE Item SET SearchTerm= "Margarine" WHERE ID="716111";
 UPDATE Item SET SearchTerm= "Margarine" WHERE ID="716113";
 UPDATE Item SET SearchTerm= "Margarine" WHERE ID="716114";
 UPDATE Item SET SearchTerm= "Margarine" WHERE ID="716116";
 UPDATE Item SET SearchTerm= "Shortening" WHERE ID="716121";
 UPDATE Item SET SearchTerm= "Peanut butter" WHERE ID="716141";
 UPDATE Item SET SearchTerm= "Cola" WHERE ID="717111";
 UPDATE Item SET SearchTerm= "Cola" WHERE ID="717112";
 UPDATE Item SET SearchTerm= "Cola" WHERE ID="717113";
 UPDATE Item SET SearchTerm= "Cola" WHERE ID="717114";
 UPDATE Item SET SearchTerm= "Ground Roast Coffee" WHERE ID="717311";
 UPDATE Item SET SearchTerm= "Ground Roast Coffee" WHERE ID="717312";
 UPDATE Item SET SearchTerm= "Instanct Coffee" WHERE ID="717324";
 UPDATE Item SET SearchTerm= "Freeze Dried Coffee" WHERE ID="717325";
 UPDATE Item SET SearchTerm= "Freeze Dried Decaf Coffee" WHERE ID="717326";
 UPDATE Item SET SearchTerm= "Instance Coffee" WHERE ID="717327";
 UPDATE Item SET SearchTerm= "Instance Coffee" WHERE ID="717411";
 UPDATE Item SET SearchTerm= "Instance Coffee" WHERE ID="717412";
 UPDATE Item SET SearchTerm= "Freeze Dried Decaf Coffee" WHERE ID="717413";
 UPDATE Item SET SearchTerm= "Potato chips" WHERE ID="718311";
 UPDATE Item SET SearchTerm= "Pork and beans" WHERE ID="718631";
 UPDATE Item SET SearchTerm= "Malt beverages" WHERE ID="720111";
 UPDATE Item SET SearchTerm= "Bourbon whiskey" WHERE ID="720211";
 UPDATE Item SET SearchTerm= "Vodka" WHERE ID="720221";
 UPDATE Item SET SearchTerm= "Vodka" WHERE ID="720222";
 UPDATE Item SET SearchTerm= "Wine" WHERE ID="720311";
 UPDATE Item SET SearchTerm=  "Fuel oil" WHERE ID="72511";
 UPDATE Item SET SearchTerm=  "Natural gas" WHERE ID="72601";
 UPDATE Item SET SearchTerm=  "Electricity" WHERE ID="72610";
 UPDATE Item SET SearchTerm=  "Natural gas" WHERE ID="72611";
 UPDATE Item SET SearchTerm=  "Natural gas" WHERE ID="72620";
 UPDATE Item SET SearchTerm=  "Electricity" WHERE ID="72621";
 UPDATE Item SET SearchTerm=  "Gasoline" WHERE ID="74712";
 UPDATE Item SET SearchTerm=  "Gasoline" WHERE ID="74713";
 UPDATE Item SET SearchTerm=  "Gasoline" WHERE ID="74714";
 UPDATE Item SET SearchTerm=  "Gasoline" WHERE ID="74715";
 UPDATE Item SET SearchTerm=  "Gasoline" WHERE ID="74716";
 UPDATE Item SET SearchTerm=  "diesel fuel" WHERE ID="74717";
 UPDATE Item SET SearchTerm=  "Gasoline" WHERE ID=" 7471A";
 UPDATE Item SET SearchTerm= "ground beef" WHERE ID="FC1101";
 UPDATE Item SET SearchTerm= "Beef Roasts" WHERE ID="FC2101";
 UPDATE Item SET SearchTerm= "Beef Steaks" WHERE ID="FC3101";
 UPDATE Item SET SearchTerm= "Beef" WHERE ID="FC4101";
 UPDATE Item SET SearchTerm= "Ham" WHERE ID="FD2101";
 UPDATE Item SET SearchTerm= "Pork Chops" WHERE ID="FD3101";
 UPDATE Item SET SearchTerm= "Pork" WHERE ID="FD4101";
 UPDATE Item SET SearchTerm= "Chicken breast" WHERE ID="FF1101";
 UPDATE Item SET SearchTerm= "Milk" WHERE ID="FJ1101";
 UPDATE Item SET SearchTerm= "Yogurt" WHERE ID="FJ4101";
 UPDATE Item SET SearchTerm= "Romaine Lettuce" WHERE ID="FL2101";
 UPDATE Item SET SearchTerm= "soft drinks" WHERE ID="FN1101";
 UPDATE Item SET SearchTerm= "soft drinks" WHERE ID="FN1102";
 UPDATE Item SET SearchTerm= "Butter" WHERE ID="FS1101";